import type { GameDefinition } from "./types";

export const gameRegistry: GameDefinition[] = [
  {
    id: "mini-brawler-3d",
    title: "Đấu Sĩ Đồ Chơi 3D",
    shortTitle: "Đấu Sĩ Mini",
    subtitle: "Đẩy đối thủ ra khỏi sàn đấu đồ chơi.",
    category: "competitive",
    modeLabel: "Đối kháng 2 người",
    durationLabel: "1-2 phút",
    difficulty: "Dễ",
    accent: "#ff7a59",
    secondaryAccent: "#ffd166",
    objective: "Dùng cú đẩy vui nhộn để đưa đối thủ ra khỏi sân.",
    mechanics: ["Chạy", "Lao tới", "Va chạm vật lý", "Tính điểm theo vòng"],
    kidTheme: "Sân đấu đồ chơi mềm, nhân vật tròn và vui.",
  },
  {
    id: "sport-action-3d",
    title: "Bóng Đá Bóng Kẹo 3D",
    shortTitle: "Bóng Kẹo",
    subtitle: "Trận bóng 1v1 nhỏ, sút bóng vào khung thành đối phương.",
    category: "competitive",
    modeLabel: "Đối kháng 2 người",
    durationLabel: "2-3 phút",
    difficulty: "Dễ",
    accent: "#2fdf84",
    secondaryAccent: "#4cc9f0",
    objective: "Đẩy và sút quả bóng lớn vào khung thành.",
    mechanics: ["Di chuyển", "Sút mạnh", "Va chạm bóng", "Ghi bàn"],
    kidTheme: "Sân bóng mini với bóng kẹo nhiều màu.",
  },
  {
    id: "arena-shooter-3d",
    title: "Đấu Trường Bóng Nước 3D",
    shortTitle: "Bóng Nước",
    subtitle: "Né và bắn bóng nước trong đấu trường một màn hình.",
    category: "competitive",
    modeLabel: "Đối kháng 2 người",
    durationLabel: "2 phút",
    difficulty: "Vừa",
    accent: "#38bdf8",
    secondaryAccent: "#a78bfa",
    objective: "Bắn trúng đối thủ bằng bóng nước, nhặt trái tim hồi máu.",
    mechanics: ["Di chuyển", "Bắn bóng nước", "Power-up", "Máu và hồi sinh"],
    kidTheme: "Bóng nước, hiệu ứng splash, không bạo lực trực diện.",
  },
  {
    id: "duo-puzzle-3d",
    title: "Cặp Đôi Mở Cổng 3D",
    shortTitle: "Mở Cổng",
    subtitle: "Hai người phối hợp đạp nút, mở cổng và cùng về đích.",
    category: "coop",
    modeLabel: "Phối hợp 2 người",
    durationLabel: "2-4 phút",
    difficulty: "Vừa",
    accent: "#f59e0b",
    secondaryAccent: "#06b6d4",
    objective: "Hai người đứng đúng vị trí để mở cổng và cùng về vùng đích.",
    mechanics: ["Nút áp lực", "Cổng khóa", "Về đích đồng thời", "Màn tăng dần"],
    kidTheme: "Khu vườn câu đố với cổng sao và bục phát sáng.",
  },
  {
    id: "chaos-kitchen-3d",
    title: "Bếp Nhà Vui Nhộn 3D",
    shortTitle: "Bếp Vui",
    subtitle: "Chia việc lấy nguyên liệu, nấu và giao món.",
    category: "coop",
    modeLabel: "Phối hợp 2 người",
    durationLabel: "2-3 phút",
    difficulty: "Vừa",
    accent: "#fb7185",
    secondaryAccent: "#facc15",
    objective: "Phối hợp lấy rau và trái cây, nấu xong rồi giao món.",
    mechanics: ["Nhặt đồ", "Bỏ vào nồi", "Giao món", "Chạy đua thời gian"],
    kidTheme: "Căn bếp gia đình an toàn, màu sáng và vui.",
  },
  {
    id: "tower-defense-3d",
    title: "Bảo Vệ Vườn Kẹo 3D",
    shortTitle: "Vườn Kẹo",
    subtitle: "Thu thập sao, xây trụ và bảo vệ căn cứ.",
    category: "coop",
    modeLabel: "Phối hợp 2 người",
    durationLabel: "3-5 phút",
    difficulty: "Khó",
    accent: "#22c55e",
    secondaryAccent: "#84cc16",
    objective: "Chặn các slime đồ chơi không chạm vào căn cứ.",
    mechanics: ["Thu tài nguyên", "Xây trụ", "Đợt tấn công", "Bảo vệ căn cứ"],
    kidTheme: "Vườn kẹo bị slime tinh nghịch tấn công.",
  },
  {
    id: "ghost-hunters-3d",
    title: "Biệt Đội Săn Ma 3D",
    shortTitle: "Săn Ma",
    subtitle: "Hai người phối hợp bắn tia sáng và bảo vệ đèn linh quang.",
    category: "coop",
    modeLabel: "Phối hợp chiến đấu",
    durationLabel: "2 phút",
    difficulty: "Vừa",
    accent: "#f97316",
    secondaryAccent: "#22d3ee",
    objective: "Cùng bảo vệ đèn trung tâm, bắn bóng ma và nhặt linh quang hồi phục.",
    mechanics: ["Bắn tia sáng", "Tạo vòng bảo vệ", "Đợt bóng ma", "Bảo vệ căn cứ"],
    kidTheme: "Sân chơi đêm vui nhộn với bóng ma tròn, đèn lồng và phép sáng an toàn.",
  },
  {
    id: "racing-casual-3d",
    title: "Xe Đồ Chơi Siêu Tốc 3D",
    shortTitle: "Xe Đồ Chơi",
    subtitle: "Đua xe đồ chơi, nhặt tăng tốc và đổi làn tránh bẫy.",
    category: "party",
    modeLabel: "Party đối kháng",
    durationLabel: "1-2 phút",
    difficulty: "Dễ",
    accent: "#ef4444",
    secondaryAccent: "#60a5fa",
    objective: "Hoàn thành 3 vòng đua trước đối thủ.",
    mechanics: ["Tăng tốc", "Đổi làn", "Nhặt boost", "Đếm vòng"],
    kidTheme: "Đường đua trong phòng đồ chơi với xe màu sắc.",
  },
  {
    id: "mini-games-3d",
    title: "Bộ Mini Game 3D",
    shortTitle: "Mini Game",
    subtitle: "Nhặt sao, né hộp gỗ và ghi điểm thật nhanh.",
    category: "party",
    modeLabel: "Party nhanh",
    durationLabel: "60 giây",
    difficulty: "Dễ",
    accent: "#c084fc",
    secondaryAccent: "#f472b6",
    objective: "Nhặt nhiều sao hơn trong thời gian giới hạn.",
    mechanics: ["Nhặt vật phẩm", "Né vật rơi", "Vòng ngắn", "Điểm nhanh"],
    kidTheme: "Sân khấu mini game với sao và hộp quà.",
  },
  {
    id: "candy-ball-3d",
    title: "Đấu Bóng Kẹo 3D",
    shortTitle: "Đấu Bóng",
    subtitle: "Đẩy bóng kẹo khổng lồ vào vùng điểm của đối thủ.",
    category: "competitive",
    modeLabel: "Đối kháng 2 người",
    durationLabel: "2 phút",
    difficulty: "Dễ",
    accent: "#f97316",
    secondaryAccent: "#22d3ee",
    objective: "Sút bóng kẹo vào khung thành đối phương để ghi điểm.",
    mechanics: ["Đẩy bóng", "Sút mạnh", "Chặn đường", "Ghi bàn nhanh"],
    kidTheme: "Sân bóng kẹo mềm, bóng lớn và nảy vui.",
  },
  {
    id: "bubble-arena-3d",
    title: "Đấu Trường Bong Bóng 3D",
    shortTitle: "Bong Bóng",
    subtitle: "Bắn bong bóng màu, né đòn và nhặt khiên.",
    category: "competitive",
    modeLabel: "Đối kháng 2 người",
    durationLabel: "2 phút",
    difficulty: "Vừa",
    accent: "#06b6d4",
    secondaryAccent: "#f0abfc",
    objective: "Dùng bong bóng làm đối thủ trượt điểm máu, nhặt tim để hồi phục.",
    mechanics: ["Bắn bong bóng", "Né đòn", "Nhặt tim", "Tính điểm hạ gục"],
    kidTheme: "Đấu trường bong bóng sáng màu, mềm và an toàn.",
  },
  {
    id: "island-box-push-3d",
    title: "Đẩy Hộp Khỏi Đảo 3D",
    shortTitle: "Đẩy Hộp",
    subtitle: "Đẩy hộp và đối thủ trên một hòn đảo đồ chơi.",
    category: "competitive",
    modeLabel: "Đối kháng 2 người",
    durationLabel: "90 giây",
    difficulty: "Vừa",
    accent: "#14b8a6",
    secondaryAccent: "#fb923c",
    objective: "Đẩy hộp khỏi đảo hoặc làm đối thủ rơi khỏi sân để ghi điểm.",
    mechanics: ["Đẩy hộp", "Lao tới", "Sàn hẹp", "Điểm theo round"],
    kidTheme: "Đảo nổi đồ chơi với hộp xốp và viền an toàn.",
  },
  {
    id: "hopper-race-3d",
    title: "Đua Thú Nhún 3D",
    shortTitle: "Thú Nhún",
    subtitle: "Đua trên đường ngắn bằng thú nhún vui nhộn.",
    category: "party",
    modeLabel: "Party đối kháng",
    durationLabel: "90 giây",
    difficulty: "Dễ",
    accent: "#f43f5e",
    secondaryAccent: "#38bdf8",
    objective: "Nhún tăng tốc, đổi làn và về đủ 3 vòng trước.",
    mechanics: ["Nhún tăng tốc", "Đổi làn", "Nhặt boost", "Tránh vật cản"],
    kidTheme: "Đường đua thú nhún nhiều màu trong sân chơi.",
  },
  {
    id: "ring-toss-3d",
    title: "Ném Vòng Vào Cọc 3D",
    shortTitle: "Ném Vòng",
    subtitle: "Canh hướng và ném vòng vào cọc phát sáng.",
    category: "competitive",
    modeLabel: "Đối kháng điểm số",
    durationLabel: "90 giây",
    difficulty: "Vừa",
    accent: "#eab308",
    secondaryAccent: "#8b5cf6",
    objective: "Ném vòng vào cọc trung tâm để ghi điểm trước đối thủ.",
    mechanics: ["Canh hướng", "Ném vòng", "Mục tiêu sáng", "Điểm chính xác"],
    kidTheme: "Trò ném vòng hội chợ với cọc sao phát sáng.",
  },
  {
    id: "toy-robot-duel-3d",
    title: "Đấu Robot Đồ Chơi 3D",
    shortTitle: "Robot Đồ Chơi",
    subtitle: "Robot nhỏ có khiên, lao tới và đẩy đối thủ.",
    category: "competitive",
    modeLabel: "Đối kháng 2 người",
    durationLabel: "2 phút",
    difficulty: "Vừa",
    accent: "#64748b",
    secondaryAccent: "#fbbf24",
    objective: "Dùng dash và khiên để đẩy robot đối thủ ra khỏi vùng an toàn.",
    mechanics: ["Dash", "Khiên", "Va chạm", "Điểm theo round"],
    kidTheme: "Robot đồ chơi bo tròn, chuyển động vui và không bạo lực.",
  },
  {
    id: "teddy-rescue-3d",
    title: "Giải Cứu Thú Bông 3D",
    shortTitle: "Cứu Thú Bông",
    subtitle: "Hai người cùng đưa thú bông về nhà an toàn.",
    category: "coop",
    modeLabel: "Phối hợp 2 người",
    durationLabel: "2-3 phút",
    difficulty: "Vừa",
    accent: "#f59e0b",
    secondaryAccent: "#ec4899",
    objective: "Một người mở đường, một người đưa thú bông về vùng nhà.",
    mechanics: ["Nhặt thú bông", "Mở cổng", "Đi cùng nhau", "Ghi điểm chung"],
    kidTheme: "Khu vui chơi thú bông với nhà sao và bục màu.",
  },
  {
    id: "bridge-builder-3d",
    title: "Xây Cầu Qua Suối 3D",
    shortTitle: "Xây Cầu",
    subtitle: "Thu vật liệu, đặt cầu và cùng vượt qua suối.",
    category: "coop",
    modeLabel: "Phối hợp 2 người",
    durationLabel: "2-4 phút",
    difficulty: "Vừa",
    accent: "#0ea5e9",
    secondaryAccent: "#a16207",
    objective: "Thu đủ vật liệu để dựng cầu rồi cùng sang bờ bên kia.",
    mechanics: ["Thu gỗ", "Xây cầu", "Mở đường", "Về đích chung"],
    kidTheme: "Dòng suối đồ chơi với các mảnh cầu phát sáng.",
  },
  {
    id: "fire-rescue-3d",
    title: "Trạm Cứu Hỏa Mini 3D",
    shortTitle: "Cứu Hỏa",
    subtitle: "Lấy nước, dập lửa hoạt hình và cứu đồ chơi.",
    category: "coop",
    modeLabel: "Phối hợp 2 người",
    durationLabel: "2-3 phút",
    difficulty: "Vừa",
    accent: "#ef4444",
    secondaryAccent: "#38bdf8",
    objective: "Hai người lấy nước và dập các đốm lửa hoạt hình trước khi hết giờ.",
    mechanics: ["Lấy nước", "Dập lửa", "Chia nhiệm vụ", "Điểm chung"],
    kidTheme: "Trạm cứu hỏa đồ chơi, lửa hoạt hình thân thiện.",
  },
  {
    id: "whack-mole-3d",
    title: "Đập Chuột Đồ Chơi 3D",
    shortTitle: "Đập Chuột",
    subtitle: "Chuột đồ chơi bật lên, ai phản xạ nhanh hơn ghi điểm.",
    category: "party",
    modeLabel: "Party phản xạ",
    durationLabel: "60 giây",
    difficulty: "Dễ",
    accent: "#a3e635",
    secondaryAccent: "#f97316",
    objective: "Chạy tới gần chuột đồ chơi và bấm hành động để ghi điểm.",
    mechanics: ["Phản xạ", "Mục tiêu bật lên", "Ghi điểm nhanh", "Round ngắn"],
    kidTheme: "Máy đập chuột hội chợ với chuột tròn dễ thương.",
  },
  {
    id: "falling-dodge-3d",
    title: "Né Vật Rơi 3D",
    shortTitle: "Né Vật Rơi",
    subtitle: "Né hộp quà rơi, nhặt sao và sống sót lâu hơn.",
    category: "party",
    modeLabel: "Party sinh tồn",
    durationLabel: "60 giây",
    difficulty: "Dễ",
    accent: "#60a5fa",
    secondaryAccent: "#facc15",
    objective: "Né hộp rơi và nhặt sao để có điểm cao hơn.",
    mechanics: ["Né vật rơi", "Nhặt sao", "Mất máu nhẹ", "Tính điểm"],
    kidTheme: "Sân chơi có hộp quà rơi chậm, hiệu ứng vui.",
  },
  {
    id: "star-maze-3d",
    title: "Nhặt Sao Trong Mê Cung 3D",
    shortTitle: "Mê Cung Sao",
    subtitle: "Chạy trong mê cung mini và nhặt sao trong 60 giây.",
    category: "party",
    modeLabel: "Party điểm số",
    durationLabel: "60 giây",
    difficulty: "Vừa",
    accent: "#facc15",
    secondaryAccent: "#22c55e",
    objective: "Tìm đường nhanh để nhặt nhiều sao hơn đối thủ.",
    mechanics: ["Mê cung nhỏ", "Nhặt sao", "Đổi hướng nhanh", "Điểm theo thời gian"],
    kidTheme: "Mê cung thấp, sáng màu và có sao phát sáng.",
  },
  {
    id: "rock-paper-magic-3d",
    title: "Oẳn Tù Tì Phép Thuật 3D",
    shortTitle: "Oẳn Tù Tì",
    subtitle: "Chọn biểu tượng phép thuật trong các vòng thật nhanh.",
    category: "party",
    modeLabel: "Party theo vòng",
    durationLabel: "60 giây",
    difficulty: "Dễ",
    accent: "#a78bfa",
    secondaryAccent: "#fb7185",
    objective: "Bấm hành động hoặc kỹ năng đúng nhịp để thắng từng vòng.",
    mechanics: ["Chọn nhanh", "Vòng ngắn", "Hiệu ứng phép", "Tính điểm round"],
    kidTheme: "Sân khấu phép thuật với đá, giấy, kéo dạng đồ chơi.",
  },
  {
    id: "tic-tac-toe-3d",
    title: "Cờ Ca Rô 3D Nâng Cấp",
    shortTitle: "Ca Rô 3D",
    subtitle: "Chiếm ô trên bàn 3D và tạo hàng ba ô.",
    category: "party",
    modeLabel: "Party chiến thuật",
    durationLabel: "2 phút",
    difficulty: "Vừa",
    accent: "#38bdf8",
    secondaryAccent: "#f97316",
    objective: "Đứng lên ô và bấm hành động để chiếm ô, tạo hàng ba ô.",
    mechanics: ["Chiếm ô", "Chặn đối thủ", "Tạo hàng", "Reset bàn"],
    kidTheme: "Bàn cờ 3D nhiều màu, ô sáng rõ và dễ nhìn.",
  },
  {
    id: "memory-match-3d",
    title: "Lật Thẻ Trí Nhớ 3D",
    shortTitle: "Trí Nhớ",
    subtitle: "Lật khối, nhớ biểu tượng và tìm cặp giống nhau.",
    category: "party",
    modeLabel: "Party trí nhớ",
    durationLabel: "2 phút",
    difficulty: "Dễ",
    accent: "#34d399",
    secondaryAccent: "#c084fc",
    objective: "Lật hai khối cùng màu để ghi điểm.",
    mechanics: ["Lật khối", "Nhớ vị trí", "Tìm cặp", "Điểm theo cặp"],
    kidTheme: "Khối đồ chơi phát sáng giúp bé luyện trí nhớ.",
  },
  {
    id: "color-catch-3d",
    title: "Bắt Bóng Màu 3D",
    shortTitle: "Bóng Màu",
    subtitle: "Mỗi người chỉ nhặt bóng đúng màu của mình.",
    category: "party",
    modeLabel: "Party phản xạ",
    durationLabel: "60 giây",
    difficulty: "Dễ",
    accent: "#ef4444",
    secondaryAccent: "#3b82f6",
    objective: "P1 nhặt bóng đỏ, P2 nhặt bóng xanh; nhặt sai bị chậm lại.",
    mechanics: ["Phân biệt màu", "Nhặt bóng", "Phạt nhẹ khi sai", "Tính điểm nhanh"],
    kidTheme: "Bóng màu lớn, dễ nhìn và phù hợp trẻ nhỏ.",
  },
  {
    id: "treasure-hunt-3d",
    title: "Đi Tìm Kho Báu 3D",
    shortTitle: "Kho Báu",
    subtitle: "Tìm chìa khóa, mở rương và chia điểm.",
    category: "coop",
    modeLabel: "Phối hợp 2 người",
    durationLabel: "2-3 phút",
    difficulty: "Vừa",
    accent: "#f59e0b",
    secondaryAccent: "#06b6d4",
    objective: "Tìm chìa khóa trước, rồi cùng mở rương kho báu.",
    mechanics: ["Tìm chìa khóa", "Mở rương", "Phối hợp vị trí", "Điểm chung"],
    kidTheme: "Đảo kho báu đồ chơi, rương vàng và chìa khóa sao.",
  },
];

export function getGameDefinition(id: string) {
  return gameRegistry.find((game) => game.id === id) ?? gameRegistry[0];
}
